### ISSUE TITLE
Install questions

### ISSUE THREAD

**Issue by Powerfultool** [saalfeldlab/n5-viewer#4]
Hi - I'm trying to install this package on a Windows 10 machine with a fresh python installation, from the folder where the package was unzipped to, but when running install.py (in an administrator privilege command prompt), I get the error below:

=================================================================

C:\installers\n5-viewer-master>python install.py C:\Users\fogim1\Fiji.app
Traceback (most recent call last):
  File "install.py", line 11, in <module>
    subprocess.call(cmd_args, cwd=base_folder)
  File "C:\Users\Fogim.CMS693GWN111545\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Fogim.CMS693GWN111545\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Fogim.CMS693GWN111545\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

=================================================================

This also happens if install.py is modified to directly use the (escaped) path, which I've checked is correct using the output of os.listdir. In addition to this, I've tried a separate machine with an Anaconda installation (from both the Anaconda prompt and cmd), but ran into the same issue. Is there something I'm missing? I'm afraid I'm not that familiar with Python package installation outside of pip etc.

**Comment by igorpisarev** [comment]
Hi @Powerfultool,
I suspect that the error is slightly misleading and the path you're providing is totally fine, but the real issue is with one of the system tools it cannot find. I realized that I forgot to specify the prerequisites in the readme so it's very likely that you don't have them installed. More specifically, it requires the following packages (their most recent versions should work):
* maven - https://maven.apache.org/ - dependency management tool
* oracle jdk - https://www.oracle.com/technetwork/java/javase/downloads/index.html - java compiler

Sorry about this, and I'll make sure to add this information to the readme. I will also look into making the plugin available through the Fiji updater.

**Comment by Powerfultool** [comment]
Thanks Igor,

This is much appreciated, and sorry for taking a while to reply - I'll give this a try as soon as I can get some time on the appropriate machine... The FIJI updater is definitely a convenient option, but I will say that we're looking into this as something that might also be appealing in the context of Micro-manager, which tends to come with vanilla ImageJ (in some cases, deliberately an older version) rather than FIJI, so the separate manual install instructions may still be handy.

Regards,
Sunil

**Comment by bogovicj** [comment]
This is shipped with Fiji now, so installation is trivial. 
Closing this issue.
